### ISSUE TITLE
Is it possible to use wildcards in selectors?

### ISSUE THREAD

**Issue by piejanssens** [meesvandongen/semantic-release-yaml#5]
```yaml
modules:
  - name: moduleABC
    properties:
      VERSION:
  - name: moduleXYZ
    properties:
      VERSION:
```

I want to set the version for any module in the given yaml file, without having to specify the module name or index. Is this possible?

**Comment by piejanssens** [comment]
Seeing lodash' documentation on `_.set`, I assume it's not possible.
However, lodash does support passing an array of paths.
It's not the same as a wildcard, but at least I could specify a number of selectors like this:
```yaml
        - file: mta.yaml
          selector:
            - modules[0].properties.VERSION
            - modules[1].properties.VERSION
            - modules[2].properties.VERSION
            - modules[3].properties.VERSION
            - modules[4].properties.VERSION
          value: ${nextRelease.version}
```
          
For that to work, the validator needs to allow string or array for the `selector`:   https://github.com/meesvandongen/semantic-release-yaml/blob/29de253dc008153bf64e0547f2cdb81b296920f5/src/verify-commands.ts#L21

This is what happens atm:
```
Your configuration for the selector option is [ 'modules[0].properties.VERSION', 'modules[1].properties.VERSION', 'modules[2].properties.VERSION', 'modules[3].properties.VERSION', 'modules[4].properties.VERSION' ].

AggregateError: 
    SemanticReleaseError: Invalid `selector` option.
```

**Comment by piejanssens** [comment]
This is my workaround, but it's not ideal because (besides the fact that the selector doesn't support an array) I have to know upfront how many 'modules' there are. If one too many 'modules' index is specified (which doesn't exit), then `_.set` will create it and corrupt the YAML file.

```yaml
        - file: mta.yaml
          selector: modules[0].properties.VERSION
          value: ${nextRelease.version}
        - file: mta.yaml
          selector: modules[1].properties.VERSION
          value: ${nextRelease.version}
```
